# Generated by Django 5.2.5 on 2025-11-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captura', '0006_captura'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturaprogresso',
            name='conversa_usada',
            field=models.BooleanField(default=False),
        ),
    ]
