# Generated by Django 5.2.5 on 2025-11-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captura', '0007_capturaprogresso_conversa_usada'),
    ]

    operations = [
        
    ]
