# Generated by Django 5.2.5 on 2025-11-25 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captura', '0009_merge_20251124_2311'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mochilaitem',
            unique_together=set(),
        ),
    ]
