# Generated by Django 5.2.5 on 2025-11-27 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captura', '0008_capturaprogresso_foi_ataque_usado'),
        ('captura', '0010_alter_mochilaitem_unique_together'),
    ]

    operations = [
    ]
